
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:8.4.0-oraclelinux9
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=blogster_api
      - MYSQL_PASSWORD=blogster_api
      - MYSQL_DATABASE=blogster
    volumes:
      - ./database/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
