
services:
  db:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=blogster_api
      - MYSQL_PASSWORD=blogster_api
      - MYSQL_DATABASE=blogster
    volumes:
      - ./data:/var/lib/mysql
